In [1]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behavior.csv'

In [ ]:
df.head()

In [ ]:
df.info()

In [2]:
df.describe(include = 'all')
#include = 'all' -> gives summery of statistical columns for numerical and categorical columns

NameError: name 'df' is not defined

In [3]:
df.isnull().sum()

NameError: name 'df' is not defined

In [4]:
#mean is not used to fill review rating because it has outliers and median is used because it has no outliers.
df['Review Rating'] = df.groupby('Category') ['Review Rating'].transform(lambda x: x.fillna(x.median()))

NameError: name 'df' is not defined

In [5]:
df.isnull().sum()

NameError: name 'df' is not defined

In [6]:
#make all the column names in smallcase and also remove spaces and add underscore
#make all columns smallcase
df.columns = df.columns.str.lower()
#add underscore in place of spaces
df.columns = df.columns.str.replace(' ','_')
#rename purchase amount(USD)
df = df.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})

NameError: name 'df' is not defined

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [13]:
#create a column age_group
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels = labels)

In [14]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [15]:
#create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Bi-Weekly' : 14,
    'Annually' : 365,
    'Every 3 Months' : 90
    
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [16]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [17]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [18]:
#here we can check that both columns have same information(if true then we remove one of them)
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [19]:
#remove promo_code_used column
df = df.drop('promo_code_used',axis = 1)

In [1]:
df.columns

NameError: name 'df' is not defined

In [21]:
pip install mysql-connector-python pandas

Requirement already satisfied: mysql-connector-python in .\AppData\Roaming\Python\Python313\site-packages (9.5.0)
Requirement already satisfied: pandas in .\AppData\Roaming\Python\Python313\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in .\anaconda3\Lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in .\anaconda3\Lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in .\anaconda3\Lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [23]:
from sqlalchemy import create_engine

username = "root"          # MySQL username
password = "1234" # MySQL password
host = "localhost"
port = "3306"              # MySQL Default Port
database = "customer_behavior"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [25]:
table_name = "customer"

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

#Read Back Sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

Data successfully loaded into table 'customer' in database 'customer_behavior'.

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365